level = [
		EMPTY,  EMPTY,  GREEN,  GREEN,  GREEN,  GREEN,  EMPTY,  EMPTY,
		EMPTY,  GREEN, GREEN,  EMPTY,  EMPTY,  GREEN,  GREEN,  EMPTY,
		GREEN,  GREEN,  ORANGE, ORANGE, ORANGE, ORANGE, GREEN,  GREEN,
		GREEN,  EMPTY,  ORANGE, YELLOW, YELLOW, ORANGE, EMPTY,  GREEN,
		GREEN,  EMPTY,  ORANGE, YELLOW, YELLOW, ORANGE, EMPTY,  GREEN,
		GREEN,  GREEN,  ORANGE, ORANGE, ORANGE, ORANGE, GREEN,  GREEN,
		EMPTY,  GREEN, GREEN,  EMPTY,  EMPTY,  GREEN,  GREEN,  EMPTY,
		EMPTY,  EMPTY,  GREEN,  GREEN,  GREEN,  GREEN,  EMPTY,  EMPTY,
];

currentLevel = 5;

load("game");