level = [
		EMPTY,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  EMPTY,
		BLUE,   BLUE,  EMPTY, BLUE,  BLUE, EMPTY, BLUE,  BLUE,
		BLUE,   EMPTY,  ORANGE, ORANGE, ORANGE, ORANGE, EMPTY, BLUE,
		BLUE,   BLUE,  ORANGE, YELLOW, YELLOW, ORANGE, BLUE,  BLUE,
		BLUE,   BLUE,  ORANGE, YELLOW, YELLOW, ORANGE, BLUE,  BLUE,
		BLUE,   EMPTY,  ORANGE, ORANGE, ORANGE, ORANGE, EMPTY, BLUE,
		BLUE,   BLUE,  EMPTY, BLUE,  BLUE, EMPTY, BLUE,  BLUE,
		EMPTY,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  EMPTY,
];

currentLevel = 4;

load("game");