level = [
		RED,    RED,    RED,    EMPTY,  EMPTY,  RED,    RED,    RED,
		RED,    ORANGE, ORANGE, EMPTY,  EMPTY,  ORANGE, ORANGE, RED,
		EMPTY,  ORANGE, YELLOW, YELLOW, YELLOW, YELLOW, ORANGE, EMPTY,
		EMPTY,  EMPTY,  YELLOW, GREEN,  GREEN,  YELLOW, EMPTY,  EMPTY,
		EMPTY,  EMPTY,  YELLOW, GREEN,  GREEN,  YELLOW, EMPTY,  EMPTY,
		EMPTY,  ORANGE, YELLOW, YELLOW, YELLOW, YELLOW, ORANGE, EMPTY,
		RED,    ORANGE, ORANGE, EMPTY,  EMPTY,  ORANGE, ORANGE, RED,
		RED,    RED,    RED,    EMPTY,  EMPTY,  RED,    RED,    RED,
];

currentLevel = 2;

load("lives");