level = [
		RED,    RED,    EMPTY,  RED,    RED,    EMPTY,  RED,    RED,
		RED,    ORANGE, ORANGE, RED,    RED,    ORANGE,ORANGE, RED,
		EMPTY,  ORANGE, YELLOW, YELLOW, EMPTY,  YELLOW,ORANGE, EMPTY,
		RED,    YELLOW, GREEN,  GREEN,  YELLOW, GREEN, YELLOW, RED,
		EMPTY,  YELLOW, GREEN,  GREEN,  YELLOW, YELLOW,ORANGE, EMPTY,
		RED,    ORANGE, YELLOW,EMPTY,  YELLOW, GREEN, ORANGE, RED,
		RED,    ORANGE, ORANGE,RED,    EMPTY,  ORANGE,ORANGE, RED,
		EMPTY,  RED,    RED,    EMPTY,  RED,    RED,   EMPTY,  RED,
];

currentLevel = 3;

load("lives");

