level = [
		EMPTY, EMPTY, RED,    RED,    RED,    RED,    EMPTY, EMPTY,
		EMPTY, RED,   RED,    ORANGE, ORANGE, RED,   RED,    EMPTY,
		RED,   RED,   ORANGE, YELLOW, YELLOW, ORANGE, RED,   RED,
		RED,   ORANGE,YELLOW, GREEN,  GREEN,  YELLOW,ORANGE, RED,
		RED,   ORANGE,YELLOW, GREEN,  GREEN,  YELLOW,ORANGE, RED,
		RED,   RED,   ORANGE, YELLOW, YELLOW, ORANGE, RED,   RED,
		EMPTY, RED,   RED,    ORANGE, ORANGE, RED,   RED,    EMPTY,
		EMPTY, EMPTY, RED,    RED,    RED,    RED,    EMPTY, EMPTY,
];

currentLevel = 1;
load("lives");
