


level = [
GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND,
GROUND, PLAYER, NONE,   NONE,   COIN,   NONE,   GROUND, NONE,   COIN,   NONE,   NONE,   NONE,   COIN,   NONE,   GROUND,
GROUND, GROUND, GROUND, NONE,   GROUND, NONE,   GROUND, NONE,   GROUND, GROUND, GROUND, NONE,   GROUND, NONE,   GROUND,
GROUND, COIN,   NONE,   NONE,   GROUND, NONE,   NONE,   NONE,   GROUND, COIN,   NONE,   NONE,   GROUND, DOOR,   GROUND,
GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND, NONE,   GROUND, NONE,   GROUND,
GROUND, COIN,   NONE,   NONE,   NONE,   COIN,   NONE,   ENEMY, NONE,   COIN,   NONE,   NONE,   NONE,   NONE,   GROUND,
GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND,
GROUND, COIN,   NONE,   NONE,   GROUND, COIN,   NONE,   NONE,   NONE,   COIN,   GROUND, NONE,   NONE,   COIN,   GROUND,
GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND, GROUND, GROUND, NONE,   GROUND, GROUND, GROUND, NONE,   GROUND,
GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND
];

currentLevel = 1;

load("game");

